In [ ]:
import sklearn
import numpy as np
import pandas as pd

In [ ]:
train = pd.read_csv("/content/train.csv")
test = pd.read_csv("/content/test.csv")

In [ ]:
train.head(10)

   id  label                                              tweet
0   1      0   @user when a father is dysfunctional and is s...
1   2      0  @user @user thanks for #lyft credit i can't us...
2   3      0                                bihday your majesty
3   4      0  #model   i love u take with u all the time in ...
4   5      0             factsguide: society now    #motivation
5   6      0  [2/2] huge fan fare and big talking before the...
6   7      0   @user camping tomorrow @user @user @user @use...
7   8      0  the next school year is the year for exams.ð...
8   9      0  we won!!! love the land!!! #allin #cavs #champ...
9  10      0   @user @user welcome here !  i'm   it's so #gr...

In [ ]:
test.tail(10)

          id                                              tweet
17187  49150  loving lifeðºð¸âï¸ð  #createyourfutu...
17188  49151  black professor demonizes, proposes nazi style...
17189  49152  learn how to think positive.  #positive   #ins...
17190  49153  we love the pretty, happy and fresh you! #teen...
17191  49154  2_damn_tuff-ruff_muff__techno_city-(ng005)-web...
17192  49155  thought factory: left-right polarisation! #tru...
17193  49156  feeling like a mermaid ð #hairflip #neverre...
17194  49157  #hillary #campaigned today in #ohio((omg)) &am...
17195  49158  happy, at work conference: right mindset leads...
17196  49159  my   song "so glad" free download!  #shoegaze ...

In [ ]:
#normal tweet
sum(train["label"] == 0)

29720

In [ ]:
#racist tweet
sum(train["label"] == 1)

2242

In [ ]:
#check if there is null or missing values
train.isnull().sum()

id       0
label    0
tweet    0
dtype: int64

**Data Cleaning**

In [ ]:
!pip install tweet-preprocessor

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: tweet-preprocessor in /usr/local/lib/python3.7/dist-packages (0.6.0)

In [ ]:
import re

#setting up punctuation
replace_n_space = re.compile("(\.)|(\;)|(\:)|(\!)|(\')|(\?)|(\,)|(\")|(\|)|(\()|(\))|(\[)|(\])|(\%)|(\$)|(\>)|(\<)|(\{)|(\})")
replace_w_space = re.compile("(<br\s/><br\s/?)|(-)|(/)|(:).")

In [ ]:
import preprocessor as p

def clean_tweets(df):
  tempArr = []
  for line in df:
    tmpL = p.clean(line)
    tmpL = replace_n_space.sub("", tmpL.lower())
    tmpL = replace_w_space.sub(" ", tmpL)
    tempArr.append(tmpL)
  return tempArr

In [ ]:
train_tweet = clean_tweets(train["tweet"])
train_tweet = pd.DataFrame(train_tweet)

In [ ]:
train["train_tweet"] = train_tweet
train.head(10)

,id,label,tweet,train_tweet
0,1,0,@user when a father is dysfunctional and is s...,when a father is dysfunctional and is so selfi...
1,2,0,@user @user thanks for #lyft credit i can't us...,thanks for credit i cant use cause they dont o...
2,3,0,bihday your majesty,bihday your majesty
3,4,0,#model i love u take with u all the time in ...,i love u take with u all the time in ur
4,5,0,factsguide: society now #motivation,factsguide society now
5,6,0,[2/2] huge fan fare and big talking before the...,2 2 huge fan fare and big talking before they ...
6,7,0,@user camping tomorrow @user @user @user @use...,camping tomorrow danny
7,8,0,the next school year is the year for exams.ð...,the next school year is the year for exams can...
8,9,0,we won!!! love the land!!! #allin #cavs #champ...,we won love the land
9,10,0,@user @user welcome here ! i'm it's so #gr...,welcome here im its so

In [ ]:
test_tweet = clean_tweets(test["tweet"])
test_tweet = pd.DataFrame(test_tweet)

test["test_tweet"] = test_tweet
test.tail(10)

,id,tweet,test_tweet
17187,49150,loving lifeðºð¸âï¸ð #createyourfutu...,loving life hyatt regency long beach
17188,49151,"black professor demonizes, proposes nazi style...",black professor demonizes proposes nazi style ...
17189,49152,learn how to think positive. #positive #ins...,learn how to think positive
17190,49153,"we love the pretty, happy and fresh you! #teen...",we love the pretty happy and fresh you
17191,49154,2_damn_tuff-ruff_muff__techno_city-(ng005)-web...,_damn_tuff ruff_muff__techno_city ng005 web 19...
17192,49155,thought factory: left-right polarisation! #tru...,thought factory left right polarisation &gt3
17193,49156,feeling like a mermaid ð #hairflip #neverre...,feeling like a mermaid
17194,49157,#hillary #campaigned today in #ohio((omg)) &am...,today in omg &amp used words like assets&ampli...
17195,49158,"happy, at work conference: right mindset leads...",happy at work conference right mindset leads t...
17196,49159,"my song ""so glad"" free download! #shoegaze ...",my song so glad free download

In [ ]:
from sklearn.model_selection import train_test_split

y = train.label.values

x_train, x_test, y_train, y_test = train_test_split(train.train_tweet.values, y, 
                                                    stratify=y, 
                                                    random_state=1, 
                                                    test_size=0.3, shuffle=True)

**Vectorize Tweet using CountVectorizer**

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer


documents = ["This is Import Data's Youtube channel",
             "Data science is my passion and it is fun!",
             "Please subscribe to my channel"]

vect = CountVectorizer()
document_term_matrix = vect.fit_transform(documents)
pd.DataFrame(document_term_matrix.toarray(), columns = vect.get_feature_names())

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

,and,channel,data,fun,import,is,it,my,passion,please,science,subscribe,this,to,youtube
0,0,1,1,0,1,1,0,0,0,0,0,0,1,0,1
1,1,0,1,1,0,2,1,1,1,0,1,0,0,0,0
2,0,1,0,0,0,0,0,1,0,1,0,1,0,1,0

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

vect = CountVectorizer(binary=True, stop_words='english')

vect.fit(list(x_train) + list(x_test))

x_train_vec = vectorizer.transform(x_train)
x_test_vec = vectorizer.transform(x_test)

In [ ]:
from sklearn import svm

svm = svm.SVC(kernel = 'linear', probability=True)

prob = svm.fit(x_train_vec, y_train).predict_proba(x_test_vec)
y_pred_svm = svm.predict(x_test_vec)

In [ ]:
from sklearn.metrics import accuracy_score
print("Accuracy score for SVC is: ", accuracy_score(y_test, y_pred_svm) * 100, '%')

Accuracy score for SVC is:  94.86912086766085 %